# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d59454447965923280a72b3c21dacf510cdf351026d7aaa28bcc237c0b2fa0432b17c2822338c6eb7778ed37d9e65b4b78648a576d9c8d9378b514edd39e442e

test:
  secret_key_base: 2b5837521ba9e29f334fe5533b8a26b006e6eab08d9555bd528191cd7e004c7469d4404954a532639775aafb15b710437e4b1ae08331d09355477e23a45c25dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
